### PR TITLE
colortest: remove recipe

### PR DESCRIPTION
**Pull request by sashko**
It belongs to meta-pelux, since it is not an IVI component and
requires QML.

Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>

### CODE REVIEW

**Comment by rpannek** [comment]
Hm, I'm not sure I agree, from the README of meta-bistro:

`This layer aggregates original IVI related software recipes for software components developed by Pelagicore.`

Which colortest quite obviously matches. What is the reason that you're moving it?

Please add this reason to the commit message so a reviewer has the chance to decide if this is necessary or not. And later that people who look at the commit log should have the chance to understand why it got removed and where it got moved to. People who use only use meta-bistro but not PELUX will wonder why they need to pull in meta-pelux just to get this recipe back.

**Comment by sashko** [comment]
> Hm, I'm not sure I agree, from the README of meta-bistro:
> 
> `This layer aggregates original IVI related software recipes for software components developed by Pelagicore.`
> 
> Which colortest quite obviously matches. What is the reason that you're moving it?

This is not `IVI related software` and requires Qml tun run, so to me, it does not match the description of the layer.

> Please add this reason to the commit message so a reviewer has the chance to decide if this is necessary or not. And later that people who look at the commit log should have the chance to understand why it got removed and where it got moved to. People who use only use meta-bistro but not PELUX will wonder why they need to pull in meta-pelux just to get this recipe back.
> 

The reason is clearly stated:
> `This belongs to meta-pelux.`

**Comment by rpannek** [comment]
> The reason is clearly stated:
>     This belongs to meta-pelux.

I respectfully disagree. There is no rational why. Something like this:

> This is not IVI related software and requires Qml tun run, so to me, it does not match the description of the layer.

Would be a more clearly stated reason, which I would understand and would be more inclined to agree with. Please add this to the commit message.

**Comment by sashko** [comment]
> > The reason is clearly stated:
> > This belongs to meta-pelux.
> 
> I respectfully disagree. There is no rational why. Something like this:
> 
> > This is not IVI related software and requires Qml tun run, so to me, it does not match the description of the layer.
> 
> Would be a more clearly stated reason, which I would understand and would be more inclined to agree with. Please add this to the commit message.

Alright, I understand. Sorry for not being clear enough.

I've added you just in case I have misunderstood the original idea of the PELUX layers. I'm still learning the stack and trying to clean everything up.

**Comment by rpannek** [comment]
I guess the ideas around the layers got quite muddy with time, the bistro distro is there for historical reasons when there was no systemd per default in the yocto distro. It's not really clear to anyone anymore what function meta-bistro actually has, so it's good that someone is going through it ant trying to clean everything up.
But perhaps the PELUX team has made some decisions about the older layers like meta-bistro which have not yet been communicated in for example blog posts?

**Comment by thenor** [comment]
> But perhaps the PELUX team has made some decisions about the older layers like meta-bistro which have not yet been communicated in for example blog posts?

No conscious decisions. I think this is a good topic for @JEderonn to sink his teeth into when he gets the chance. It would be good to have a common view of what goes where and why.

**Comment by martin-ejdestig** [comment]
> If there is no effort taken to add background information to commit messages then I really feel that it doesn't make sense to add me as a reviewer, it's just wasting everybody's time.

...

> But perhaps the PELUX team has made some decisions about the older layers like meta-bistro which have not yet been communicated in for example blog posts?

Just to chime in here... I think the commit message should be more clear regardless of if this has been done or not.

I ignored this pr just because of me not knowing what was going on. And, even if something has been discussed in the team and it is clear today does not mean that it is clear a year from now.

**Comment by JEderonn** [comment]
https://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines

A side note: Colortest is a must-have for board bring-up in very IVI project

**Comment by thenor** [comment]
@sashko Is this moved to meta-pelux also?

**Comment by sashko** [comment]
> @sashko Is this moved to meta-pelux also?

I believe it has to be. I won't do it until this change is merged.

**Pull request closed without merging**
