### PR TITLE
linux-raspberrypi: add CONFIG_IKCONFIG

### PR DESCRIPTION
**Pull request by sashko**
Add CONFIG_IKCONFIG to defconfig to enable
access to the kernel configuration file through /proc/config.gz.

This simplifies debugging kernel related issues.

Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>

### CODE REVIEW

**Comment by martin-ejdestig** [comment]
Not at work so can not check in detail. But why is it not enabled by default?

Looks like it should be if I e.g. check https://github.com/raspberrypi/linux/blob/rpi-3.14.y/arch/arm/configs/bcmrpi_defconfig . Might not be the correct one, unsure which case of http://git.yoctoproject.org/cgit/cgit.cgi/meta-raspberrypi/tree/recipes-kernel/linux/linux-raspberrypi.inc?h=thud#n17 we use without access to my work computer. The CONFIG_IKCONFIG* lines have not been touched for > 5 years in the bcmrpi_defconfig I linked to at least.

**Comment by sashko** [comment]
Hm... You seem to be right. This is what `defconfig` looks like:

    CONFIG_IKCONFIG=m
    CONFIG_IKCONFIG_PROC=y

So, alternatively, we could just set `CONFIG_IKCONFIG` to `y` or auto load it.

**Comment by sashko** [comment]
Yup, `CONFIG_IKCONFIG=y` was enough.

**Comment by martin-ejdestig** [comment]
I wonder where it is changed from 'y' to 'm' though.

**Comment by martin-ejdestig** [comment]
Ah, sorry. I accidentally typed 3.14 instead of 4.14. It is set to 'm' in https://github.com/raspberrypi/linux/blob/rpi-4.14.y/arch/arm/configs/bcmrpi_defconfig .

Only question left then is if we want to follow upstream and keep this as a module (could just `modprobe` if we really want to check config runtime) or change it. Approving and letting you decide.

**Comment by sashko** [comment]
# modprobe configs
    modprobe: ERROR: could not insert 'configs': Cannot allocate memory

    # insmod ./configs.ko 
    insmod: ERROR: could not insert module ./configs.ko: Cannot allocate memory

**Comment by sashko** [comment]
@martin-ejdestig ping.

**Comment by martin-ejdestig** [comment]
Hum... You did not update the commit... ? Or find out why you cannot load modules... ?

**Comment by sashko** [comment]
@Pelagicore/pelux ping.

**Pull request merged**
