### PR TITLE
qtwayland-native_git.bbappend: Remove QtWayland bbappend

### PR DESCRIPTION
**Pull request by GordanM**
* The component branch and source revision should be stated
in the original meta-qt5 recipe

### CODE REVIEW

**Comment by GordanM** [comment]
I've added this pull request to jethro as that is what we are currently using - though it might/should be moved to master as well?

**Comment by breakreturn** [comment]
Maintainers might be able to point you to some guidelines about this, but AFAIK the principle is that as long as a change goes into the branch that corresponds to the latest release branch of yocto, it should also be in master. Only when the branch becomes "old", in the sense that it is no longer the latest, will there be a difference to master.

Let's have a confirmation from the maintainers though.

**Comment by socec** [comment]
We use a strategy where we do pull requests and development on the master branch and then merge to the latest "Yocto release" branch, jethro in this case. Could you please add it to master instead?

**Comment by GordanM** [comment]
Ok, so that's the work flow. Got it.

**Comment by rpannek** [comment]
Btw it is stated in the readme https://github.com/Pelagicore/meta-bistro#branching but perhaps you won't find it if you don't read the complete readme?

**Comment by frznlogic** [comment]
@rpannek do you have any suggestions to make it easier to find?

**Pull request closed without merging**
