### PR TITLE
WIP: Add temporary patch for linux-tegra

### PR DESCRIPTION
**Pull request by mardy**
The patch has been submitted upstream as well:
https://github.com/madisongh/meta-tegra/pull/101

Signed-off-by: Alberto Mardegan <amardegan@luxoft.com>

### CODE REVIEW

**Comment by sashko** [comment]
@mardy are you sure you it has to go to `master`? aren't you guys using `rocko` atm?

**Comment by mardy** [comment]
We are using `master` in our manifest file, but the hash we reference is also in the `rocko` branch, so I guess it's a better idea if I rebase this.

**Comment by mardy** [comment]
Hi! I prefer to see if I can find some other solution, since the upstream maintainer didn't approve the patch. Let's keep it floating for some time :-)

**Comment by mardy** [comment]
I've found a better way to do this, without touching the meta-tegra layer: https://github.com/madisongh/meta-tegra/pull/101

So, we can drop this.

**Pull request closed without merging**
