### PR TITLE
openblas: add openblas linear algebra library

### PR DESCRIPTION
**Pull request by TSAnsari**
openblas is an optimized basic linear algebra subprogram(blas) library.
This library is dependency of KittAI's snowboy Wakeword Engine to be
used in Alexa service. The recipe is taken from the following source
and modified.

https://github.com/intel/intel-iot-refkit/tree/master/meta-refkit-extra/recipes-convnet/openblas

Signed-off-by: Tariq Ansari <tansari@luxoft.com>

### CODE REVIEW

**Comment by TSAnsari** [comment]
Since this recipe is copied from https://github.com/intel/intel-iot-refkit/tree/master/meta-refkit-extra/recipes-convnet/openblas and modified a little, please do look if the license header part of the recipe is done correctly or not.

**Comment by sashko** [comment]
> openblas: add openblas 

I used a buttery butter on this butter bread.

**Comment by sashko** [comment]
Also, why not bump it to the latest version?

**Comment by TSAnsari** [comment]
> > openblas: add openblas
> 
> I used a buttery butter on this butter bread.

fixed

**Comment by TSAnsari** [comment]
> Also, why not bump it to the latest version?

fixed

**Pull request merged**
