### PR TITLE
packagegroup-bistro-utils: add connman-client to bistro-utils

### PR DESCRIPTION
**Pull request by sashko**
tools-testapps package group that contains connman-client has been
removed from the -dev images in @c2ca4d557010. We need this tool to
work with connman though.

Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>

### CODE REVIEW

**Comment by martin-ejdestig** [comment]
Does it make sense to have it here? Is there a way to add it only if ConnMan is pulled in? Or should it be somewhere else? (Thinking that meta-bistro should be generic and what if NM or systmed-networkd is used... I can not see how ConnMan was originally pulled in to PELUX).

**Comment by sashko** [comment]
> Does it make sense to have it here? Is there a way to add it only if ConnMan is pulled in? Or should it be somewhere else?

It depends on why we need it: to debug/work with connman or because it is essential for some functionality. If the former, we can for sure make it a dependency of connman.

**Comment by JEderonn** [comment]
In general, connmanctl is not required, but very useful to control ConnMan functionality. I would say it's mandatory during development, but not required to have it in production system.
So I vote to have it in all PELUX images.

**Comment by sashko** [comment]
> So I vote to have it in all PELUX images.

All or -dev only?

**Comment by JEderonn** [comment]
>  I can not see how ConnMan was originally pulled in to PELUX).

Me neither. This is very strange since I know it was present before Connectivity Manager was added.

**Comment by JEderonn** [comment]
> All or -dev only?

All

**Pull request closed without merging**
