### PR TITLE
bistro distro: cleanup

### PR DESCRIPTION
**Pull request by GordanM**
Remove reference to bistro as a yocto distribution.
Remove image recipes from this layer.

Signed-off-by: Gordan Markuš <gordan.markus@pelagicore.com>

### CODE REVIEW

**Comment by GordanM** [comment]
#103 and #105. 
This is a staged commit that won't be merged yet but is staged as a notification that we will be removing bistro as a Yocto distribution.

**Comment by rpannek** [comment]
And like @zeenix mentioned in a different commit the two words prefix is really not that good, I'd rather see the colon removed.

**Comment by GordanM** [comment]
@DunderRoffe please check the edited comment.

**Comment by DunderRoffe** [comment]
Awesome stuffs

**Pull request merged**
