### PR TITLE
Removed itzam and libspotify from support recipes.

### LINKED ISSUE #22: Are we still using libitzam?
In recipes-support there is a recipe for libitzam. This code is dual licensed -- simplified BSD for open source projects like ours and commercial license for closed source projects. If we want anyone to use meta-bistro, we need to make it clear that using libitzam commercially requires a commercial license from upstream. More here: http://coyotegulch.scottrobertladd.net/products/itzam/c/index.html

If we're not using itzam, perhaps we remove this in order to avoid any confusion for downstream?

### PR DESCRIPTION
**Pull request by jeremiah**
Signed-off-by: Jeremiah C. Foster <jeremiah.foster@pelagicore.com>

This patch closes #22 and #23. It should not have a negative impact on PCL, but it might. I have not tested the impact of these deletions on the build. Should I do that before they're merged? I think that they should have no impact.

### CODE REVIEW

**Comment by breakreturn** [comment]
If you have the possibility to test a build, then I think it would be great if you could test it!

**Comment by frznlogic** [comment]
I'm merging this if noone objects in the next 24 hours. @rpannek @socec Are you ok with it?

**Comment by socec** [comment]
Tested on a project that I am working on, can't see any problems.

**Comment by jeena** [comment]
Yeah itzam is depricated and I don't think we use libspotify in any project anymore.

**Comment by Gagi2k** [comment]
I think we might want to use libspotify in the future for qtivi stuff, but i think it's better to add it again later on, as it's unknown when that will happen

**Comment by frznlogic** [comment]
We had a talk about it and apparently libspotify isn't deprecated anymore, they are working on it, but nothing available yet. But I agre with @Gagi2k, lets remove it and re-add it when it's needed again.

**Pull request merged**
