### PR TITLE
common-api-c++-dbus: remove deprecated patches

### PR DESCRIPTION
**Pull request by GordanM**

### CODE REVIEW

**Comment by GordanM** [comment]
These patches were moved from version 3.1.5 to 3.1.10 by Oleksander.

I am quite sure that one of these patches is not applicable (0001-Adds-required-dependencies-to-pc-file.patch). For the second one I cannot be sure, so I would appreciate some feedback from @jonte and Oleksander (I cannot reference his user for some reason). Was this relevant for the project you were working on? Thanks!

**Comment by rpannek** [comment]
Thanks for the description.

**Comment by jonte** [comment]
@GordanM Sorry, but I am not familiar with this change :-/ We are not using CommonAPI, so I think, from our current project's perspective, it is safe to remove this patch.

**Comment by GordanM** [comment]
@jonte thanks for the feedback!

**Pull request merged**
