### PR TITLE
Add CommonAPI 3.1.5 integration

### PR DESCRIPTION
**Pull request by breakreturn**
Add code generators and cmake integration framework. Includes
a couple of patches to upstream D-Bus runtime .pc and cmake
files

### CODE REVIEW

**Comment by breakreturn** [comment]
Agree. I've moved the files to layers/ivi

I guess there might be an intention to also have the files in classes/ that are layer specific moved to layers/ as well, but that will require changes to how the "conditional layers paths" are set up right?

**Comment by rpannek** [comment]
It'd be nice if you could squash this so it would be just one commit.

And I guess we didn't have anything in classes which needed to go into layers before but let's see what the others say.

**Comment by socec** [comment]
I vote for keeping the "classes" as they are now.

You introduce maven handling which is currently directly used only in this layer specific code you wrote, but is in my opinion also nice to have if meta-bistro users will want to use maven for something else. The "classes" directory already has some files that are not used directly in meta-bistro. I see it as a new feature that meta-bistro brings in.

**Comment by frznlogic** [comment]
I kind of agree to igor but also not, if possible I'd prefer to use the classes from a meta-maven repository if it's available, however I'm not sure how to implement that and/or if it's available.

**Comment by frznlogic** [comment]
That said, I think we can pull it in unless there's something else we need to discuss first.

**Comment by breakreturn** [comment]
I've squashed the commits. I think we can change the classes part laster, this commit is useful (and needed) as it is right now. I'd be glad to help out later with fixing the classes related things.

**Pull request merged**
