### PR TITLE
Removing all rights reserved, added homepage.

### PR DESCRIPTION
**Pull request by jeremiah**
Signed-off-by: Jeremiah C. Foster <jeremiah@jeremiahfoster.com>

### CODE REVIEW

**Comment by jonte** [comment]
Thanks for the patch Jeremiah. Could you please put quotes around the value for the HOMEPAGE assignment?

**Comment by frznlogic** [comment]
I have no objections to this. Anyone object?

**Comment by jonte** [comment]
Could you also squash the commits which fix errors in previous commits? This will make the history look nicer, and allow us to bisect easier. You can use `git rebase  --interactive HASH` for this.

**Comment by jeremiah** [comment]
Squashed! :-)

**Comment by frznlogic** [comment]
Something strange happened in that squash, you changed the commit id's of Igor's changes as well. Could you check what happened?

**Comment by jeremiah** [comment]
I don't think it is a big deal, I think what happened is that my signed-off-by got attached to earlier commits via the squash, but that shouldn't be a problem?

**Comment by jeremiah** [comment]
If things are all messed up, I'll take the blame! :-)

**Pull request merged**
