### PR TITLE
packagegroup-bistro-utils: remove tools preset at tools-debug

### PR DESCRIPTION
**Pull request by sashko**
Removed tools that are already part of tools-testapps which is included
in PELUX -dev images.

Also removed openssh-sftp-server as it is also part of the -dev images.

Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>

### CODE REVIEW

**Comment by sashko** [comment]
So you don't look for too long:
* https://github.com/Pelagicore/meta-pelux/blob/master/recipes-core/images/core-image-pelux-minimal-dev.bb#L10
* http://cgit.openembedded.org/openembedded-core/tree/meta/recipes-core/packagegroups/packagegroup-core-tools-debug.bb?h=thud

**Comment by martin-ejdestig** [comment]
Hum, in https://github.com/Pelagicore/meta-pelux/pull/329 you remove tools-testapps?

**Comment by sashko** [comment]
> Hum, in [Pelagicore/meta-pelux#329](https://github.com/Pelagicore/meta-pelux/pull/329) you remove tools-testapps?

I've meant `tools-debug` :)

**Comment by martin-ejdestig** [comment]
I do not know the history here, so a bit unsure. Does it perhaps make sense to keep openssh-sftp-server in packagegroup-bistro-utils and not add it manually in -dev images in meta-pelux?

**Comment by sashko** [comment]
> Does it perhaps make sense to keep openssh-sftp-server in packagegroup-bistro-utils and not add it manually in -dev images in meta-pelux?

openssh-sftp-server is used by Qt Creator to deploy apps on the image, so they can be quickly tested by Qt/QML developers, so it's is needed by default in -dev image. Tools from the package group will only be needed sometimes by some developers.

**Comment by martin-ejdestig** [comment]
> Although.. it is probably better to keep it.
Yes, after your description above it sounds like it is best to have it in both places.

**Pull request merged**
