### PR TITLE
systemd: stop low-level messages on console

### PR DESCRIPTION
**Pull request by sashko**
Lower kernel.printk values to the ones Ubuntu has to get rid of
unnecessary low-level messages.

Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>

### CODE REVIEW

**Comment by martin-ejdestig** [comment]
Install in /usr/lib? From https://www.freedesktop.org/software/systemd/man/sysctl.d.html : 

"Packages should install their configuration files in /usr/lib/ (distribution packages) or /usr/local/lib/ (local installs). Files in /etc/ are reserved for the local administrator,"

**Comment by martin-ejdestig** [comment]
Do we want this in meta-bistro or in meta-pelux? I am not sure myself. `99-pelux.conf`like it is named now => meta-pelux?

**Comment by sashko** [comment]
> Do we want this in meta-bistro or in meta-pelux? I am not sure myself. `99-pelux.conf`like it is named now => meta-pelux?

Well, we want them for all the images, right?

**Comment by sashko** [comment]
> Install in /usr/lib? From https://www.freedesktop.org/software/systemd/man/sysctl.d.html :
> 
> "Packages should install their configuration files in /usr/lib/ (distribution packages) or /usr/local/lib/ (local installs). Files in /etc/ are reserved for the local administrator,"

Done. I have also renamed the file to avoid confusions - my original idea was to have universal one for PELUX, but I guess it makes sense to have a separate one.

**Comment by martin-ejdestig** [comment]
> > Do we want this in meta-bistro or in meta-pelux? I am not sure myself. `99-pelux.conf`like it is named now => meta-pelux?
> 
> Well, we want them for all the images, right?

All images of what? :) PELUX yes, all images that use meta-bistro... I do not know. Approving and will let you take decision.

Or wait, `install -d ${D}${sysconfdir}/sysctl.d` is wrong.

**Comment by sashko** [comment]
> > > Do we want this in meta-bistro or in meta-pelux? I am not sure myself. `99-pelux.conf`like it is named now => meta-pelux?
> > 
> > 
> > Well, we want them for all the images, right?
> 
> All images of what? :) PELUX yes, all images that use meta-bistro... I do not know. Approving and will let you take decision.
> 
> Or wait, `install -d ${D}${sysconfdir}/sysctl.d` is wrong.

It's been changed to `${D}${libdir}/sysctl.d/`

**Comment by martin-ejdestig** [comment]
Not for `-d`, only for `-m`. At least that what it looks like to me in d6db55a24aea8e5b85a67ad427914216a903f13a which is the most recent commit as far as I can tell.

**Comment by sashko** [comment]
will go to meta-pelux instead.

**Pull request closed without merging**
